import Head from 'next/head'
import CarsList from "../components/CarsList"

export default function Home({cars}) {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello world</h1>
      <CarsList cars={cars} />
    </div>
  )
}
export const getStaticProps = async () => {
  const res = await fetch(`${process.env.HOST}/car`);
  const cars = await res.json();
  return {
    props: {
      cars
    }
  }
}